### ISSUE TITLE
parks inconsistent across tiles

### ISSUE THREAD

**Issue by burritojustice** [mapzen/d3-vector-tiles#21]
Parks/greenspace that span tiles are not drawn consistently. 
Presdio, SF:
![d3 presido](https://cloud.githubusercontent.com/assets/3979711/10469616/81d2b8b6-71bb-11e5-97e4-dd5b3fe91224.png)
San Bruno Mountain, San Mateo County:
![d3 san bruno mountain](https://cloud.githubusercontent.com/assets/3979711/10469620/8a956d40-71bb-11e5-8929-f5b036609da3.png)

**Comment by burritojustice** [comment]
actual extent of parks/greenspace 
![presido and san bruno mountains](https://cloud.githubusercontent.com/assets/3979711/10469707/649d5b38-71bc-11e5-8968-3a89f765afd8.png)

**Comment by nvkelso** [comment]
Fixed via a758d7183a7dd633f8d13b6ef350995ea0923505.
