### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by petulla** [mapzen/d3-vector-tiles#22]
hi all
the index.html of this demo series is throwing quite a few nan value errors in the projection in chrome (in the thousands at higher zoom levels). zoomed-out, the browser sometimes crashes.

i haven't tested across devices but hoping you can clarify.

**Comment by migurski** [comment]
Thanks @petulla! I’ve checked in Chrome, and I’m seeing the same thing as you. Based on a quick examination, it looks like there might be some malformed path values in the source tiles. I’ll have a deeper look, probably Monday when I’m back in the office.

**Comment by migurski** [comment]
Hi again. We’ve dug a little deeper, and our best guess is that there’s something the matter between binary vector tile formatting and possibly-aging D3 code in this demo. Diagnosis of this one might be a bit slow, please bear with us.

**Comment by petulla** [comment]
@migurski Thanks. One note: I don't see the errors on your live demo. Might be worth checking the D3 version as well.

**Comment by migurski** [comment]
Looks like @nvkelso is working on this in https://github.com/nvkelso/d3-vector-tiles/commit/9a0720628124a73ef14895544b902610fbd5c726, I’ll reassign this ticket to reflect that.

**Comment by nvkelso** [comment]
Fixed via a758d7183a7dd633f8d13b6ef350995ea0923505.

**Comment by nvkelso** [comment]
@petulla The NaN errors have been fixed, as well as a few other burrs – the white circles have been removed, and all roads and all parks are now shown (before those were splotchy do to a pre-processing bug). General perforance has been improved, too, by skipping building processing at mid zooms. Please let us know if you have any other questions or comments!
